souvikinator/notion-to-md

notion-to-md.js
When parsing annotated text, if the text has leading or trailing spaces, the parsed text doesn't render as expected in markdown. Here are some examples.
This change fixes this problem by shifting the leading and trailing spaces outside the parsed text.
=> Fix leading and trailing space breaking annotation parsing

src/notion-to-md.ts
Fix #11 
Example:
The next image block:
turns into:
```md
```
=> feat: Add caption as alt to images

src/utils/notion.ts
Per https://github.com/souvikinator/notion-to-md/issues/13
Retrieves all children if `totalPage == null` 
Original Implementation [violated spec](https://developers.notion.com/reference/pagination): `start_cursor` should be treated as an opaque value, and `next_cursor` should be used to provide the next `start_cursor`. Deriving from the id may not be acceptable. Typically `has_more` can be used to determine whether there are more results; this implementation checks for the existence of `next_cursor` instead.
=> Add support for retrieving all children.

src/utils/md.ts
Tab spaces are prepended to text right after `\n`.
Issue intended to fix: #21
=> Bug fix - Add spacing for text with newline

src/notion-to-md.ts
Fix for issue #23.
In order to keep support to prior versions of @notionhq/client@1.0.0, `rich_text` is added in the logical OR expression.
I've tested it in a personal project and it works OK.
Converts to:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis neque vel odio lobortis posuere nec sit amet erat. Morbi congue velit quis ante accumsan volutpat. Nam ornare enim eu metus consectetur facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut convallis erat, eget egestas magna. Nunc non orci at ante placerat pretium in id justo. Morbi a mattis lacus. Nulla tempus, massa a cursus porta, risus leo varius urna, euismod tristique ante metus vitae lacus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis neque vel odio lobortis …
```
=> (patch) check for rich_text property

src/notion-to-md.ts, src/types/index.ts, src/utils/md.ts, src/utils/notion.ts
This fixes issue #18 and even supports nested list items.
I solved this problem by introducing a new hook function that runs after each block's children is listed. I then "inject" a new property into the block object `number`, which just increments from 1 to max, and then in the rendering stage, use the property to render the numbered list bullets.
Result:
🎉
=> Added support for numbered lists

src/notion-to-md.ts, src/utils/md.spec.ts, src/utils/md.ts
The toggle function don't support empty toggles. 
Here the error on empty toggle:
```bash
// notion-to-md.js
const toggle_summary = block.toggle.rich_text[0].plain_text;
TypeError: Cannot read properties of undefined (reading 'plain_text')
```
In this PR you will find: 
* Tests to fix the bug
* Changes in `utils/md#toggle`: 
* accept undefined as title
* returns content if title is undefined
* returns empty string if title and content are empty
=> fix: handle empty titles in toggle

src/utils/notion.ts
**Description**
A little fix for the ordered list numbering continuing from the previous ordered list. 
**Difference**
INPUT:
_List 1 in Notion:_
1\. apple
2\. banana
3\. orange
... other content from notion page
_List 2 in Notion:_
1\. car
2\. truck
3\. bike
OUTPUT BEFORE THESE CHANGES:
_List 1 in notion-to-md_
1\. apple
2\. banana
3\. orange
... other content from notion page
_List 2 in notion-to-md_
4\. apple
5\. banana
6\. orange
OUTPUT AFTER THESE CHANGES:
_List 1 in notion-to-md_
1\. apple
2\. banana
3\. orange
... other content from notion page
_List 2 in notion-to-md_
1\. apple
2\. banana
3\. orange
=> FIX: Ordered Lists Numbering Continue From Previous List

src/notion-to-md.ts, src/types/index.ts
Hi awesome library!
While working on a project of mine, I realized I needed to be able to trace down the block ids corresponding to a given markdown object.
I added a quick little addition to the MarkdownBlock idea to do this.
Let me know if there's anything else this needs!
(PS: Sorry about auto-formatting, editor-based)
=> Add comments, add blockIds to MarkdownBlock

README.md, src/notion-to-md.spec.ts, src/notion-to-md.ts
- want to support returning default parsed value from custom transformers
- this PR adds support for returning default parsed values if the custom transformer returns `false`
- resolves #50
- do not return value if custom transformer returns `false` 
- added unit tests to test actual implementation of custom transformers
=> Add default return value in setCustomTransformer callback function

src/notion-to-md.ts, src/types/index.ts, src/utils/md.spec.ts, src/utils/md.ts
This PR implements markdown formatting of block equations and inline equations.
Inline equations are enclosed between single dollar `$` symbols and block equations are enclosed by double dollar `$$` symbols:
```md
$inline$
$$
block
$$
```
This is supported by [remark-math](https://github.com/remarkjs/remark-math/tree/main/packages/remark-math#use) from unified.js and by [GitHub Markdown](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions).
=> feat: add markdown for equation and inline equations

README.md
Removes the following error when running the test code to write a file
`ReferenceError: fs is not defined`
=> Added Node.js file system module to test code 

.gitignore, src/notion-to-md.ts, src/types/index.ts
[`b35e168` (#74)](https://github.com/souvikinator/notion-to-md/pull/74/commits/b35e168550afeb3e8794aa54f7daa87db84c6f87)
- **Fix column and column_list handler**
more to add...
=> Refactor code

src/notion-to-md.ts
fix the bug when querying children blocks for synced_block.
=>  add support for synced_block.

README.md
This is correcting location of config object in Readme
It was added incorrectly  as property of Notion Client. I have moved it to show as property on NotionToMarkdown
=> fix: config for separateChildPage now correctly on NotionToMarkdown

src/types/index.ts
Update `CustomTransformer` type to support the `false` return.  #93 
**Before:**
=> Update CustomTransformer type

src/notion-to-md.ts
blocksToMarkdown fails for unsupported block types.
For example: `Block type ai_block is not supported via the API for your bot type.`
=> Skip unsupported block type.

src/utils/md.ts
The regex had 2 issues:
- taking the non formatted text
- not taking into account whitespaces and line breaks which would not display content following the first block/line
=> Fix regex callout heading

src/types/index.ts
Yesterday Notion changed some type definitions, making them incompatible with the types defined in by notion-to-md. Those changes are [here](https://github.com/makenotion/notion-sdk-js/blob/eed58030649895b95ab9b97e2959f77bab19cd62/src/api-endpoints.ts#L759) and [here](https://github.com/makenotion/notion-sdk-js/blob/eed58030649895b95ab9b97e2959f77bab19cd62/src/api-endpoints.ts#L4683).
I went looking for a bit of robustness so this doesn't get broken by arbitrary changes again from Notion in the future. Looks like another package [notion types](https://www.npmjs.com/package/notion-types) would keep up with changes like this (albeit less precisely than the aliases defined here. Unless the maintainers are averse to adding additional packages I'll see if this could be a more permanent …
=> matching interface changes in notion package

src/notion-to-md.ts
👋 hey
We have a case where we're getting a `child_page` mixed in, which causes a crash 💥
=> Skip children of `table` that are not `table_row`
